version: '3'

services:
  traefik:
    image: traefik
    command: 
      - "--api" 
      - "--docker"
      - "--consul"
      - "--consul.endpoint=consul:8500"
    ports:
      - "8080:80"     # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consul:
    image: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    labels:
      - "traefik.port=8500"
      - "traefik.frontend.rule=PathPrefixStrip:/consul/"
      - "traefik.frontend.rule=PathPrefix:/ui/,/v1/"
  den-travak:
    image: den-travak-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8234:8080
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefixStrip:/den-travak/"
    environment:
      - spring.profiles.active=container
  recommendation:
    image: recommendation-app:0.0.1-SNAPSHOT
    restart: unless-stopped
    depends_on:
      - consul
    ports:
      - 8235:8082
    labels:
      - "traefik.port=8082"
      - "traefik.frontend.rule=PathPrefixStrip:/recommendation/"