spring:
  application:
    name: den-travak
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health-check
        healthCheckInterval: 20s
        prefer-ip-address: true
server:
  port: 8080